"""Cross-check Script.xml values against Roland's official MIDI Implementation.

Inputs (read-only):
  research/script-schema.json                 (from extract_script_schema.py)
  research/generated/midi-implementation.pdf.txt
      text of docs/AX Synth docs.pdf ("AX-Synth MIDI Implementation",
      Roland Europe, Jan 2010), extracted with research/tools/pdf2txt.py

Output: research/generated/crosscheck-midi-implementation.md

The PDF text extraction is imperfect (wrapped lines, stray parentheses), so
doc rows are parsed leniently and every mismatch should be eyeballed
against the PDF before being treated as real.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
schema = json.loads((ROOT / "research/script-schema.json").read_text(encoding="utf-8"))
doc = (ROOT / "research/generated/midi-implementation.pdf.txt").read_text(encoding="utf-8")

SECTIONS = {  # doc section title -> script structType
    "Setup": "Setup",
    "System Common": "SystemCommon",
    "System Controller": "SystemController",
    "Patch Common": "PatchCommon",
    "Patch Common MFX": "PatchCommonMFX",
    "Patch Common Chorus": "PatchCommonChorus",
    "Patch Common Reverb": "PatchCommonReverb",
    "Patch TMT (Tone Mix Table)": "PatchTMT",
    "Patch Tone": "PatchTone",
}

ROW = re.compile(r"^(#\s*)?([0-9A-F]{2}) ([0-9A-F]{2})\s+(.*)$")
TOTAL = re.compile(r"^00 00 ([0-9A-F]{2}) ([0-9A-F]{2}) Total Size")
RANGE = re.compile(r"\(\s*(\d+)\s*(?:~|-|–)\s*(\d+)\s*\)?")


def parse_doc():
    lines = doc.splitlines()
    cur = None
    rows = {}
    totals = {}
    for i, raw in enumerate(lines):
        l = raw.strip()
        t = l.lstrip("❍").strip()
        if t in SECTIONS and (i + 1 < len(lines)):
            cur = SECTIONS[t]
            rows.setdefault(cur, [])
            continue
        if cur is None:
            continue
        m = TOTAL.match(l)
        if m:
            totals[cur] = int(m.group(1), 16) * 128 + int(m.group(2), 16)
            cur = None
            continue
        m = ROW.match(l)
        if m:
            nibbled = bool(m.group(1))
            off = int(m.group(2), 16) * 128 + int(m.group(3), 16)
            rest = m.group(4)
            # description may continue on following lines (nibbled rows)
            desc = rest
            j = i + 1
            while j < len(lines) and not ROW.match(lines[j].strip()) and not TOTAL.match(lines[j].strip()) and j < i + 12:
                desc += " " + lines[j].strip()
                j += 1
            bits = re.match(r"((?:[01a-d]{4} ?){1,2})", rest)
            name = re.sub(r"^((?:[01a-d]{4} ?){1,2})", "", rest).strip()
            rm = RANGE.search(desc)
            rows[cur].append({
                "offset": off, "nibbled": nibbled, "desc": name,
                "range": [int(rm.group(1)), int(rm.group(2))] if rm else None,
                "reserve": "reserve" in desc, "ignored": "<*>" in desc,
                "doc_line": i + 1,
            })
    return rows, totals


def fmt(o):
    return f"{o // 128:02X} {o % 128:02X}"


def main():
    rows, totals = parse_doc()
    st = schema["structTypes"]
    out = ["# Cross-check: Script.xml vs official MIDI Implementation", "",
           "Generated by `research/tools/crosscheck_midi_impl.py`. Doc = `docs/AX Synth docs.pdf`"
           " (text in `research/generated/midi-implementation.pdf.txt`).", "",
           "Offsets are relative to the block start, shown as 7-bit `MSB LSB`.", ""]
    summary = []
    machine = {}
    for doc_sec, stype in SECTIONS.items():
        vals = [c for c in st[stype]["children"] if c["kind"] == "value"]
        # for union structs, compare only generic (non 'effect-param') members
        by_off = {}
        union = stype in ("PatchCommonMFX", "PatchCommonChorus", "PatchCommonReverb")
        for v in vals:
            if union and "-" in v["name"]:  # '<effect>-<param>' union members
                continue
            by_off.setdefault(v["offset"], []).append(v)
        size_tok = st[stype]["size_raw"].split()
        script_size = 0
        for b in size_tok:
            script_size = script_size * 128 + int(b, 16)
        drows = rows.get(stype, [])
        for r in drows:
            vs = by_off.get(r["offset"], [])
            status = "match"
            if not vs:
                status = "doc-only"
            elif r["range"] and vs[0].get("range") and r["range"] != vs[0]["range"]:
                status = f"range differs (doc {r['range']})"
            machine[f"{stype}:{r['offset']}"] = {"status": status, "desc": r["desc"],
                                                 "doc_range": r["range"], "nibbled": r["nibbled"],
                                                 "doc_line": r["doc_line"]}
        matched = mism = missing_in_script = 0
        lines = []
        covered = {v["offset"] + k for v in vals if v["type"] == "string"
                   for k in range(1, v["size_bytes"])}  # e.g. 12-byte patchName
        for r in drows:
            vs = by_off.get(r["offset"], [])
            if not vs and r["offset"] in covered:
                matched += 1
                continue
            if not vs:
                if not r["reserve"]:
                    missing_in_script += 1
                    lines.append(f"| {fmt(r['offset'])} | *(none)* | {r['desc'][:50]} | doc {r['range']} | - | **not in script** |")
                continue
            v = vs[0]
            exp_size = 4 if r["nibbled"] and v["type"] == "int4x4" else None
            problems = []
            if r["range"] and v.get("range") and r["range"] != v["range"]:
                problems.append("range differs")
            if r["nibbled"] and not v["type"].startswith(("int2x4", "int4x4", "int3x4")):
                problems.append("doc says nibbled, script type " + v["type"])
            if not r["nibbled"] and v["type"] not in ("int1x7", "string"):
                problems.append("script nibbled, doc not")
            if problems:
                mism += 1
                lines.append(f"| {fmt(r['offset'])} | `{v['name']}` | {r['desc'][:50]} | doc {r['range']} | script {v.get('range')} {v['type']} | {'; '.join(problems)} |")
            else:
                matched += 1
        # script values with no doc row
        doc_offs = {r["offset"] for r in drows}
        extra = [v for o, vl in by_off.items() for v in vl if o not in doc_offs and v["type"] != "string"]
        for v in extra:
            lines.append(f"| {fmt(v['offset'])} | `{v['name']}` | *(no doc row)* | - | script {v.get('range')} | **not in doc** |")
        size_note = f"doc total {totals.get(stype)}, script size {script_size}"
        if totals.get(stype) != script_size:
            size_note += " **(DIFFERS)**"
        summary.append(f"| {stype} | {len(drows)} | {matched} | {mism} | {missing_in_script} | {len(extra)} | {size_note} |")
        out.append(f"## {stype} (doc: {doc_sec})\n")
        out.append(size_note + "\n")
        if lines:
            out.append("| offset | script name | doc description | doc range | script | issue |")
            out.append("|---|---|---|---|---|---|")
            out.extend(lines)
        else:
            out.append("All non-reserved doc rows matched (offset, range, encoding).")
        out.append("")
    head = ["## Summary", "", "| struct | doc rows | match | mismatch | doc-only (non-reserve) | script-only | size |",
            "|---|---|---|---|---|---|---|", *summary, ""]
    out[6:6] = head
    p = ROOT / "research/generated/crosscheck-midi-implementation.md"
    p.write_text("\n".join(out), encoding="utf-8")
    (ROOT / "research/generated/crosscheck.json").write_text(json.dumps(machine, indent=1), encoding="utf-8")
    print("\n".join(head))


if __name__ == "__main__":
    main()
