// AX-Synth Web Editor: UI built from model.json (generated by
// research/tools/build_web_model.py from Roland's own data model).
import { buildDT1, hex, addrToInt, encodeValue, userPatchAddress } from "./sysex.js";
import { Synth } from "./midi.js";
import { Patch, display, options, routing } from "./patch.js";

const $ = (id) => document.getElementById(id);
const logEl = $("log");
function log(text) {
  const t = new Date().toISOString().slice(11, 23);
  logEl.textContent += `${t} ${text}\n`;
  if (logEl.textContent.length > 400000) logEl.textContent = logEl.textContent.slice(-300000);
  logEl.scrollTop = logEl.scrollHeight;
}

const model = await (await fetch("model.json")).json();
let patch = Patch.initial(model);
let original = patch.clone(); // snapshot of the last Read / Load / Open / INIT
let a8eTemplate = null; // bytes of the last opened .a8e (keeps its Setup/System on save)
let setup = null; // Setup switches read from the synth (for the routing check)
const synth = new Synth(log);
let connected = false;
const controls = new Map(); // path -> {update()}
const linked = new Set(); // tones (0-based) edited together

// ---------------------------------------------------------------- sending
const pending = new Map();
let flushTimer = null;
function transmit(change) {
  if (!connected || !$("live").checked) return;
  pending.set(change.address, change); // latest value per address wins while dragging
  if (!flushTimer) flushTimer = setTimeout(flush, 25);
}
function flush() {
  flushTimer = null;
  for (const c of pending.values()) synth.send(buildDT1(c.address, Array.from(c.data)), 10).catch(fail);
  pending.clear();
}
function sendNow(address, data, gap = 20) {
  if (connected && $("live").checked) synth.send(buildDT1(address, Array.from(data)), gap).catch(fail);
}
// Drop throttled edits inside a block that is about to be sent whole, so a
// stale value can't land after it.
function dropPending(block) {
  const b = model.blocks.find((x) => x.name === block);
  const start = patch.blockAddress(block);
  for (const addr of [...pending.keys()]) if (addr >= start && addr < start + b.size) pending.delete(addr);
}
function fail(e) {
  console.error(e);
  log(`ERROR ${e.message}`);
  setStatus(e.message, "err");
}
function setStatus(text, cls) {
  const s = $("status");
  s.textContent = text;
  s.className = `status ${cls}`;
}

async function sendWholePatch() {
  pending.clear();
  $("verify").textContent = "sending…";
  $("verify").className = "verify";
  for (const b of model.blocks) {
    await synth.send(buildDT1(patch.blockAddress(b.name), Array.from(patch.blocks[b.name])), 60);
  }
  await new Promise((r) => setTimeout(r, 100));
  const bad = [];
  for (const b of model.blocks) {
    const got = await synth.request(patch.blockAddress(b.name), b.size);
    if (hex(got) !== hex(patch.blocks[b.name])) bad.push(b.name);
  }
  $("verify").textContent = bad.length ? `✗ read-back differs: ${bad.join(", ")}` : "✓ sent and verified";
  $("verify").className = `verify ${bad.length ? "bad" : "ok"}`;
  log(bad.length ? `verify FAILED for ${bad.join(", ")}` : "verify OK: the synth holds exactly the patch we sent");
}

async function readBlocks(base) {
  const blocks = {};
  for (const b of model.blocks) blocks[b.name] = await synth.request(base + b.offset, b.size);
  return new Patch(model, blocks);
}

// ---------------------------------------------------------------- controls
function makeControl(path) {
  const p = model.params[path];
  const row = document.createElement("div");
  row.className = "ctl" + (p.schemaOnly ? " schemaonly" : "");
  const label = document.createElement("label");
  label.textContent = p.label;
  label.title = `${p.help}\n\n${path}`;
  row.append(label);

  let input;
  const out = document.createElement("output");
  if (p.control === "select" || p.control === "wave" || p.control === "effectType" || isAssign(path)) {
    row.classList.add("wide");
    input = document.createElement("select");
    const fill = () => {
      input.innerHTML = "";
      for (const [v, text] of choiceList(path)) input.add(new Option(text, v));
    };
    fill();
    input.addEventListener("change", () => onChange(path, Number(input.value)));
    controls.set(path, { update: () => { if (isAssign(path)) fill(); input.value = String(patch.get(path)); } });
    row.append(input);
  } else if (p.control === "text") {
    return null;
  } else {
    input = document.createElement("input");
    input.type = "range";
    input.min = p.range[0];
    input.max = p.range[1];
    input.step = 1;
    input.addEventListener("input", () => {
      onChange(path, Number(input.value));
      out.value = display(p, Number(input.value), model.waves);
    });
    controls.set(path, { update: () => { const v = patch.get(path); input.value = v; out.value = display(p, v, model.waves); } });
    row.append(input, out);
  }
  input.title = label.title;
  return row;
}

function isAssign(path) {
  return /mfxControlAssign\d$/.test(path);
}

function choiceList(path) {
  const p = model.params[path];
  if (p.control === "wave") return [[0, "0: OFF"], ...model.waves.map((w, i) => [i + 1, `${i + 1}: ${w}`])];
  if (isAssign(path)) {
    const t = model.effects.mfx.types.find((x) => x.number === patch.effectType("mfx"));
    const labels = t && t.assign ? t.assign.labels : ["OFF"];
    return labels.map((l, i) => [i, l]);
  }
  if (p.control === "effectType") return p.enum.map((n, i) => [i, `${i}: ${n}`]);
  return options(p);
}

function effectKindOf(path) {
  return Object.keys(model.effects).find((k) => model.effects[k].discriminator === path);
}

function onChange(path, value) {
  const p = model.params[path];
  try {
    if (p.control === "effectType") {
      const kind = effectKindOf(path);
      dropPending(p.block);
      const [block, type] = patch.changeEffectType(kind, value);
      sendNow(block.address, block.data);
      sendNow(type.address, type.data);
      renderEffects();
      refresh();
      return;
    }
    const changes = patch.setLinked(path, value, [...linked]);
    changes.forEach(transmit);
    if (changes.length > 1) scheduleRefresh();
    else scheduleStatus();
  } catch (e) {
    fail(e);
  }
}

// ---------------------------------------------------------------- layout
const effectSections = {};
function renderPanels() {
  const nav = $("tabs");
  const main = $("panels");
  const extra = [{ id: "changes", title: "Changes" }, { id: "system", title: "System (read-only)" }, { id: "log", title: "MIDI log" }];
  for (const pan of [...model.panels, ...extra]) {
    const btn = document.createElement("button");
    btn.textContent = pan.title;
    btn.dataset.panel = pan.id;
    btn.onclick = () => showPanel(pan.id);
    nav.append(btn);
    if (pan.id === "log") continue;
    const div = document.createElement("div");
    div.id = `panel-${pan.id}`;
    div.hidden = true;
    main.append(div);
    if (pan.id === "system") {
      div.innerHTML = `<section class="sec"><h2>System and Setup (read from the synth, not editable here)</h2>
        <p class="help">Press "Read from synth" to fill this in. Change these on the synth's panel if needed.</p>
        <table class="ro" id="systable"></table></section>`;
      continue;
    }
    if (pan.id === "changes") {
      div.innerHTML = `<section class="sec"><h2>Changes since the last Read / Load / Open / New</h2>
        <p class="help">Reset puts one value back (effect settings come back as a whole effect). Revert all sends the original patch again and verifies it.</p>
        <div class="row"><button id="revertall">Revert all</button></div>
        <table class="ro changes" id="changetable"></table></section>`;
      continue;
    }
    if (pan.tone !== undefined || pan.id === "matrix") div.append(linkBar());
    if (pan.id === "effects") div.append(effectsIntro());
    for (const s of pan.sections) {
      if (!s.params.length) continue;
      const sec = section(s.title, s.help);
      const grid = sec.querySelector(".grid");
      for (const path of s.params) {
        const c = makeControl(path);
        if (c) grid.append(c);
      }
      div.append(sec);
      if (pan.id === "effects") {
        const kind = { "fx.mfx": "mfx", "fx.chorus": "chorus", "fx.reverb": "reverb" }[s.id];
        if (kind) {
          const holder = document.createElement("div");
          effectSections[kind] = holder;
          div.append(holder);
        }
      }
    }
  }
  $("revertall").onclick = revertAll;
  showPanel("common");
}

function linkBar() {
  const bar = document.createElement("div");
  bar.className = "linkbar";
  bar.innerHTML = `<b>Edit tones together:</b> `;
  for (let t = 0; t < 4; t++) {
    const l = document.createElement("label");
    l.className = "check";
    const cb = document.createElement("input");
    cb.type = "checkbox";
    cb.dataset.tone = t;
    cb.onchange = () => {
      if (cb.checked) linked.add(t);
      else linked.delete(t);
      for (const other of document.querySelectorAll(`.linkbar input[data-tone="${t}"]`)) other.checked = cb.checked;
    };
    l.append(cb, ` Tone ${t + 1}`);
    bar.append(l);
  }
  const hint = document.createElement("span");
  hint.className = "hint";
  hint.textContent = "An edit on a ticked tone is applied to all ticked tones (like Shift + TONE SELECT in Roland's Editor).";
  bar.append(hint);
  return bar;
}

function effectsIntro() {
  const box = document.createElement("section");
  box.className = "sec";
  box.innerHTML = `<h2>Effects routing</h2><ul class="routing" id="routing"></ul>
    <p class="help">The AX-Synth has <b>one</b> MFX, one Chorus and one Reverb per sound. For a second modulation effect,
    use the tones' LFOs (LFO section of each Tone tab: DEPTH TVA = tremolo, DEPTH PAN = auto-pan, DEPTH PITCH = vibrato,
    DEPTH TVF = wah; tick "Edit tones together" to set all tones at once) or an MFX combination type
    (27 TREMOLO CHORUS, 66–77 e.g. OVERDRIVE->CHORUS, CHORUS->DELAY).</p>`;
  return box;
}

function section(title, help) {
  const sec = document.createElement("section");
  sec.className = "sec";
  sec.innerHTML = `<h2></h2><p class="help"></p><div class="grid"></div>`;
  sec.querySelector("h2").textContent = title;
  sec.querySelector("p").textContent = help || "";
  return sec;
}

function renderEffects() {
  for (const [kind, holder] of Object.entries(effectSections)) {
    for (const path of controls.keys()) {
      if (model.params[path].union && model.params[path].union[0] === kind && model.params[path].union[1] > 0) controls.delete(path);
    }
    holder.innerHTML = "";
    const n = patch.effectType(kind);
    const t = model.effects[kind].types.find((x) => x.number === n);
    if (!t || !t.params.length) continue;
    const sec = section(`${kind.toUpperCase()} ${n}: ${t.name}${t.category ? ` (${t.category})` : ""}`, t.description);
    const grid = sec.querySelector(".grid");
    for (const path of t.params) {
      const c = makeControl(path);
      if (c) grid.append(c);
    }
    holder.append(sec);
  }
}

function showPanel(id) {
  for (const b of $("tabs").children) b.classList.toggle("active", b.dataset.panel === id);
  for (const d of $("panels").children) d.hidden = d.id !== `panel-${id}`;
  $("logpanel").hidden = id !== "log";
}

// ---------------------------------------------------------------- status: routing + changes
let statusFrame = 0;
function scheduleStatus() {
  if (!statusFrame) statusFrame = requestAnimationFrame(() => { statusFrame = 0; updateStatus(); });
}
let refreshFrame = 0;
function scheduleRefresh() {
  if (!refreshFrame) refreshFrame = requestAnimationFrame(() => { refreshFrame = 0; refresh(); });
}

function updateStatus() {
  const r = routing(patch, setup);
  const ul = $("routing");
  ul.innerHTML = "";
  for (const item of r) {
    const li = document.createElement("li");
    li.className = item.level;
    li.textContent = `${{ ok: "✓", warn: "⚠", info: "·" }[item.level]} ${item.text}`;
    ul.append(li);
  }
  const warn = r.some((x) => x.level === "warn");
  tab("effects").textContent = `${model.panels.find((p) => p.id === "effects").title}${warn ? " ⚠" : ""}`;

  const changes = patch.diff(original);
  tab("changes").textContent = `Changes (${changes.length})`;
  const table = $("changetable");
  table.innerHTML = "";
  for (const c of changes) {
    const p = model.params[c.path];
    const tr = document.createElement("tr");
    const where = c.path.replace(/^fm\.pat\./, "").replace(/^tone\[(\d)\]\..*/, (_, t) => `Tone ${+t + 1}`).split(".")[0];
    tr.innerHTML = `<td></td><td></td><td></td><td></td><td></td>`;
    tr.children[0].textContent = where;
    tr.children[1].textContent = p.label;
    tr.children[2].textContent = display(p, c.from, model.waves);
    tr.children[3].textContent = `→ ${display(p, c.to, model.waves)}`;
    const b = document.createElement("button");
    b.textContent = "Reset";
    b.onclick = () => resetOne(c.path);
    tr.children[4].append(b);
    table.append(tr);
  }
  if (!changes.length) table.innerHTML = `<tr><td>No changes.</td></tr>`;
}
function tab(id) {
  return [...$("tabs").children].find((b) => b.dataset.panel === id);
}

function resetOne(path) {
  const p = model.params[path];
  try {
    const kind = p.union ? p.union[0] : effectKindOf(path);
    if (kind && (p.union ? p.union[1] > 0 : true)) {
      // effect type or member: restore the whole effect block (Editor pattern: block, then type byte)
      dropPending(p.block);
      patch.blocks[p.block] = Uint8Array.from(original.blocks[p.block]);
      const disc = model.params[model.effects[kind].discriminator];
      sendNow(patch.blockAddress(p.block), patch.blocks[p.block]);
      sendNow(patch.address(disc), encodeValue(disc, patch.effectType(kind)));
      renderEffects();
    } else {
      transmit(patch.set(path, original.get(path), false));
    }
    refresh();
  } catch (e) {
    fail(e);
  }
}

function revertAll() {
  patch = original.clone();
  renderEffects();
  refresh();
  if (connected) sendWholePatch().catch(fail);
}

function refresh() {
  $("name").value = patch.name();
  for (const c of controls.values()) c.update();
  updateStatus();
}

function renderSystem(areas) {
  const rows = model.readonly.params.map((p) => {
    const bytes = areas[p.area];
    if (!bytes) return "";
    const v = bytes.slice(p.offset, p.offset + p.size).reduce((a, b) => a * (p.type === "int4x4" ? 16 : 128) + b, 0);
    return `<tr><td>${p.label}</td><td>${display(p, v, model.waves)}</td></tr>`;
  });
  $("systable").innerHTML = rows.join("");
  setup = {};
  for (const p of model.readonly.params) {
    if (p.area === "setup" && areas.setup) setup[p.path.split(".").pop()] = areas.setup[p.offset];
  }
}

// ---------------------------------------------------------------- actions
function setPatch(p, sendIt) {
  patch = p;
  original = p.clone();
  renderEffects();
  refresh();
  if (sendIt && connected) sendWholePatch().catch(fail);
}

$("connect").onclick = async () => {
  try {
    setStatus("connecting…", "off");
    const reply = await synth.connect(model.identityReply);
    connected = true;
    setStatus("Connected: Roland AX-Synth", "on");
    log(`Identity Reply ${hex(reply)}`);
    for (const id of ["read", "send", "loadslot"]) $(id).disabled = false;
    $("connect").disabled = true;
    await readFromSynth();
  } catch (e) {
    fail(e);
  }
};

async function readFromSynth() {
  const p = await readBlocks(model.meta.temporaryPatch);
  const areas = {};
  for (const a of model.readonly.areas) areas[a.name] = await synth.request(addrToInt(a.address.split(" ").map((x) => parseInt(x, 16))), a.size);
  renderSystem(areas);
  setPatch(p, false);
  log(`read Temporary Patch "${patch.name()}"`);
}

$("read").onclick = () => readFromSynth().catch(fail);
$("send").onclick = () => sendWholePatch().catch(fail);
$("loadslot").onclick = async () => {
  try {
    const n = Number($("slot").value);
    const p = await readBlocks(userPatchAddress(n));
    log(`read stored sound ${n} "${p.name()}" (read-only); sending it to the Temporary Patch`);
    setPatch(p, true);
  } catch (e) {
    fail(e);
  }
};
$("init").onclick = () => setPatch(Patch.initial(model), true);
$("open").onchange = async (ev) => {
  const f = ev.target.files[0];
  if (!f) return;
  try {
    const bytes = new Uint8Array(await f.arrayBuffer());
    const p = Patch.fromA8e(model, bytes);
    a8eTemplate = bytes;
    log(`opened ${f.name}: "${p.name()}" (only the patch is sent, not the file's System/Setup)`);
    setPatch(p, true);
  } catch (e) {
    fail(e);
  }
  ev.target.value = "";
};
$("save").onclick = () => {
  const blob = new Blob([patch.toA8e(a8eTemplate)], { type: "application/octet-stream" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `${patch.name().replace(/[^\w.-]+/g, "_") || "patch"}.a8e`;
  a.click();
  URL.revokeObjectURL(a.href);
};
$("name").onchange = () => {
  try {
    transmit(patch.set("fm.pat.common.patchName", $("name").value));
    scheduleStatus();
  } catch (e) {
    fail(e);
  }
};
$("copylog").onclick = () => navigator.clipboard.writeText(logEl.textContent);
$("clearlog").onclick = () => { logEl.textContent = ""; };

for (const t of model.factory) $("slot").add(new Option(`${t.slot}  ${t.name}  (${t.family})`, t.n));
renderPanels();
renderEffects();
refresh();
log(`model: ${Object.keys(model.params).length} parameters from ${model.meta.generator}`);
if (!navigator.requestMIDIAccess) setStatus("No Web MIDI in this browser: use Edge or Chrome", "err");

// ?selftest: offline UI check with a fake MIDI output that records what
// would be sent. Logs one SELFTEST line (used by the headless-Edge check).
if (new URLSearchParams(location.search).has("selftest")) {
  const sent = [];
  synth.output = { send: (m) => sent.push(hex(m)) };
  connected = true;
  const wait = (ms) => new Promise((r) => setTimeout(r, ms));
  const count = (kind) => effectSections[kind].querySelectorAll(".ctl").length;
  const res = [];
  for (const [kind, n] of [["mfx", 39], ["mfx", 63], ["chorus", 2], ["reverb", 3]]) {
    onChange(model.effects[kind].discriminator, n);
    res.push(`${kind}=${n}:${count(kind)}`);
  }
  await wait(200);
  // stale-edit check: drag a reverb member, then change the reverb type at once
  sent.length = 0;
  onChange("fm.pat.rev.srvHall-tm", 32800);
  onChange("fm.pat.rev.reverbType", 4);
  await wait(300);
  const last = sent[sent.length - 1] || "";
  res.push(`typeChangeMsgs=${sent.length} lastIsType=${last.startsWith("F0 41 10 00 00 3C 12 1F 00 06 00 04")}`);
  // routing: reverb on, sends zero -> warning; send up -> ok
  patch.set("fm.pat.rev.reverbLevel", 100);
  for (let t = 0; t < 4; t++) patch.set(`fm.pat.tone[${t}].toneReverbSendLevelMFX`, 0);
  patch.set("fm.pat.mfx.mfxReverbSendLevel", 0);
  patch.set("fm.pat.cho.chorusOutputSelect", 0);
  updateStatus();
  const revWarn = [...document.querySelectorAll("#routing li.warn")].some((li) => li.textContent.includes("Reverb"));
  patch.set("fm.pat.mfx.mfxReverbSendLevel", 60);
  updateStatus();
  const revOk = [...document.querySelectorAll("#routing li.ok")].some((li) => li.textContent.includes("Reverb"));
  res.push(`routingWarn=${revWarn} routingOk=${revOk} effectsTab="${tab("effects").textContent}"`);
  // linked tones
  linked.add(0); linked.add(2);
  onChange("fm.pat.tone[0].tvfCutoffFrequency", 33);
  res.push(`linked=${[0, 1, 2, 3].map((t) => patch.get(`fm.pat.tone[${t}].tvfCutoffFrequency`)).join("/")}`);
  linked.clear();
  // changes + revert
  updateStatus();
  const nChanges = patch.diff(original).length;
  connected = false;
  revertAll();
  res.push(`changes=${nChanges} afterRevert=${patch.diff(original).length} tab="${tab("changes").textContent}"`);
  res.push(`controls=${document.querySelectorAll(".ctl").length}`);
  log(`SELFTEST ${res.join(" ")}`);
}
