// AX-Synth Web Editor: UI built from model.json (generated by
// research/tools/build_web_model.py from Roland's own data model).
import { buildDT1, buildUserPatchDT1, hex, addrToInt, encodeValue, userPatchAddress } from "./sysex.js";
import { Synth } from "./midi.js";
import { Patch, display, options, routing, signalPath } from "./patch.js";

const $ = (id) => document.getElementById(id);
const logEl = $("log");
function log(text) {
  const t = new Date().toISOString().slice(11, 23);
  logEl.textContent += `${t} ${text}\n`;
  if (logEl.textContent.length > 400000) logEl.textContent = logEl.textContent.slice(-300000);
  logEl.scrollTop = logEl.scrollHeight;
}

const model = await (await fetch("model.json")).json();
let patch = Patch.initial(model);
let original = patch.clone(); // snapshot of the last Read / Load / Open / INIT
let a8eTemplate = null; // bytes of the last opened .a8e (keeps its Setup/System on save)
let setup = null; // Setup switches read from the synth (for the routing check)
let lastVerify = null; // {ok, when, name}
let lastSlot = null; // memory slot last loaded (default for "Store in synth slot")
const synth = new Synth(log);
let connected = false;
const controls = new Map(); // path -> [{update()}] (a setting can have several controls, e.g. a diagram shortcut)
function addControl(path, c) {
  if (!controls.has(path)) controls.set(path, []);
  controls.get(path).push(c);
  return c;
}
function removeControl(path, c) {
  const list = controls.get(path);
  if (list) controls.set(path, list.filter((x) => x !== c));
}
function syncControls(path) {
  for (const c of controls.get(path) || []) c.update();
}
const linked = new Set(); // tone columns (0-based) edited together

const TONE_PANELS = model.panels.filter((p) => p.tone !== undefined);
const tonePath = (path, t) => path.replace(/^fm\.pat\.tone\[\d\]/, `fm.pat.tone[${t}]`);

// ---------------------------------------------------------------- sending
const pending = new Map();
let flushTimer = null;
function transmit(change) {
  if (!connected || !$("live").checked) return;
  pending.set(change.address, change); // latest value per address wins while dragging
  if (!flushTimer) flushTimer = setTimeout(flush, 25);
}
function flush() {
  flushTimer = null;
  for (const c of pending.values()) synth.send(buildDT1(c.address, Array.from(c.data)), 10).catch(fail);
  pending.clear();
}
function sendNow(address, data, gap = 20) {
  if (connected && $("live").checked) synth.send(buildDT1(address, Array.from(data)), gap).catch(fail);
}
// Drop throttled edits inside a block that is about to be sent whole, so a
// stale value can't land after it.
function dropPending(block) {
  const b = model.blocks.find((x) => x.name === block);
  const start = patch.blockAddress(block);
  for (const addr of [...pending.keys()]) if (addr >= start && addr < start + b.size) pending.delete(addr);
}
function fail(e) {
  console.error(e);
  log(`ERROR ${e.message}`);
  setStatus(e.message, "err");
}
function setStatus(text, cls) {
  const s = $("status");
  s.textContent = text;
  s.className = `status ${cls}`;
}

// "Are you sure?" dialog. Resolves true on OK. (?selftest answers OK automatically.)
let autoConfirm = false;
function confirmBox(title, text, ok = "Continue") {
  if (autoConfirm) return Promise.resolve(true);
  const d = $("confirm");
  $("confirm-title").textContent = title;
  $("confirm-text").textContent = text;
  $("confirm-ok").textContent = ok;
  return new Promise((resolve) => {
    const done = (v) => { d.close(); $("confirm-ok").onclick = $("confirm-cancel").onclick = d.oncancel = null; resolve(v); };
    $("confirm-ok").onclick = () => done(true);
    $("confirm-cancel").onclick = () => done(false);
    d.oncancel = () => done(false);
    d.showModal();
    $("confirm-cancel").focus();
  });
}
const unsaved = () => patch.diff(original).length;
const unsavedNote = () => (unsaved() ? ` Your ${unsaved()} change${unsaved() === 1 ? "" : "s"} to "${patch.name()}" will be lost unless you saved them (Save .a8e).` : "");

function setVerify(text, cls) {
  for (const el of document.querySelectorAll(".verify")) {
    el.textContent = text;
    el.className = `verify ${cls}`;
  }
}

async function sendWholePatch() {
  if (!connected) {
    setVerify("Not connected: click Connect first.", "bad");
    return;
  }
  pending.clear();
  setVerify("Sending the whole sound…", "busy");
  for (const b of model.blocks) {
    await synth.send(buildDT1(patch.blockAddress(b.name), Array.from(patch.blocks[b.name])), 60);
  }
  await new Promise((r) => setTimeout(r, 100));
  const bad = [];
  for (const b of model.blocks) {
    const got = await synth.request(patch.blockAddress(b.name), b.size);
    if (hex(got) !== hex(patch.blocks[b.name])) bad.push(b.name);
  }
  lastVerify = { ok: !bad.length, when: new Date(), name: patch.name() };
  setVerify(bad.length ? `✗ The synth's copy differs (${bad.join(", ")}). Try again.`
                       : `✓ The synth now plays exactly this sound ("${patch.name()}"), checked ${lastVerify.when.toLocaleTimeString()}.`,
            bad.length ? "bad" : "ok");
  log(bad.length ? `verify FAILED for ${bad.join(", ")}` : "verify OK: the synth holds exactly the patch we sent");
  scheduleStatus();
}

async function readBlocks(base) {
  const blocks = {};
  for (const b of model.blocks) blocks[b.name] = await synth.request(base + b.offset, b.size);
  return new Patch(model, blocks);
}

// ---------------------------------------------------------------- controls
// One control. `bare` = no label (tone-column cells, whose label is the row header).
function makeControl(path, bare = false) {
  const p = model.params[path];
  if (p.control === "text") return null;
  const row = document.createElement("div");
  row.className = "ctl" + (bare ? " cell" : "") + (p.schemaOnly ? " schemaonly" : "") + (p.simple ? " simple" : "") + (p.level ? " level" : "");
  row.dataset.path = path;
  const tip = `${p.label}\n\n${p.help}\n\n${path}`;
  if (!bare) {
    const label = document.createElement("label");
    label.textContent = p.short || p.label;
    label.title = tip;
    row.append(label);
  }

  // ↺: back to the value from the last Read / Load / Open / New
  const reset = document.createElement("button");
  reset.className = "reset";
  reset.textContent = "↺";
  reset.title = "Reset to the value before your change";
  reset.onclick = () => resetOne(path);

  const mark = () => {
    const changed = patch.get(path) !== original.get(path);
    row.classList.toggle("changed", changed);
    reset.hidden = !changed;
  };

  let input;
  const out = document.createElement("output");
  let explain = null;
  if (p.control === "select" || p.control === "wave" || p.control === "effectType" || isAssign(path)) {
    row.classList.add("wide");
    input = document.createElement("select");
    const fill = () => {
      input.innerHTML = "";
      for (const [v, text] of choiceList(path)) input.add(new Option(text, v));
    };
    fill();
    if (p.enumLong) {
      explain = document.createElement("div");
      explain.className = "explain";
    }
    const describe = () => {
      if (!explain) return;
      const i = options(p).findIndex(([v]) => v === patch.get(path));
      explain.textContent = i >= 0 ? `${p.enum[i]}: ${p.enumLong[i].text}` : "";
    };
    input.addEventListener("change", async () => {
      if (p.control === "effectType") {
        const kind = effectKindOf(path);
        const ok = await confirmBox(`Change the ${kind === "mfx" ? "MFX" : kind} type?`,
          `The new type starts from its default settings; the current ${kind === "mfx" ? "MFX" : kind} settings are replaced. (You can undo with ↺.)`, "Change type");
        if (!ok) { input.value = String(patch.get(path)); return; }
      }
      onChange(path, Number(input.value)); describe(); mark();
    });
    row.ctl = addControl(path, { update: () => { if (isAssign(path)) fill(); input.value = String(patch.get(path)); describe(); mark(); }, mark });
    row.append(input);
  } else {
    input = document.createElement("input");
    input.type = "range";
    input.min = p.range[0];
    input.max = p.range[1];
    input.step = 1;
    input.addEventListener("input", () => {
      onChange(path, Number(input.value));
      out.value = display(p, Number(input.value), model.waves);
      mark();
    });
    row.ctl = addControl(path, { update: () => { const v = patch.get(path); input.value = v; out.value = display(p, v, model.waves); mark(); }, mark });
    row.append(input, out);
  }
  row.append(reset);
  if (explain) row.append(explain);
  input.title = tip;
  return row;
}

function isAssign(path) {
  return /mfxControlAssign\d$/.test(path);
}

function choiceList(path) {
  const p = model.params[path];
  if (p.control === "wave") return [[0, "0: OFF"], ...model.waves.map((w, i) => [i + 1, `${i + 1}: ${w}`])];
  if (isAssign(path)) {
    const t = model.effects.mfx.types.find((x) => x.number === patch.effectType("mfx"));
    const labels = t && t.assign ? t.assign.labels : ["OFF"];
    return labels.map((l, i) => [i, l]);
  }
  if (p.control === "effectType") return p.enum.map((n, i) => [i, `${i}: ${n}`]);
  if (p.enumLong) return options(p).map(([v, l], i) => [v, p.enumLong[i].short ? `${l} (${p.enumLong[i].short})` : l]);
  return options(p);
}

function effectKindOf(path) {
  return Object.keys(model.effects).find((k) => model.effects[k].discriminator === path);
}

function onChange(path, value) {
  const p = model.params[path];
  try {
    if (p.control === "effectType") {
      const kind = effectKindOf(path);
      dropPending(p.block);
      const [block, type] = patch.changeEffectType(kind, value);
      sendNow(block.address, block.data);
      sendNow(type.address, type.data);
      renderEffects();
      refresh();
      return;
    }
    const changes = patch.setLinked(path, value, [...linked]);
    changes.forEach(transmit);
    if (changes.length > 1) scheduleRefresh();
    else { syncControls(path); scheduleStatus(); }
  } catch (e) {
    fail(e);
  }
}

// ---------------------------------------------------------------- layout
const effectSections = {};
const effectViews = {};
let effectView = "mfx"; // which effect's settings the Effects tab shows (chosen in the diagram)
function setEffectView(kind) {
  effectView = kind;
  for (const [k, v] of Object.entries(effectViews)) v.hidden = k !== kind;
  if ($("diagram")) $("diagram").innerHTML = diagram(signalPath(patch));
}
function renderPanels() {
  const nav = $("tabs");
  const main = $("panels");
  const panels = [
    { id: "help", title: "Start here" },
    model.panels.find((p) => p.id === "common"),
    { id: "tones", title: "Tones 1–4" },
    ...model.panels.filter((p) => p.tone === undefined && p.id !== "common"),
    { id: "changes", title: "Changes" }, { id: "system", title: "System (read-only)" }, { id: "log", title: "MIDI log" },
  ];
  for (const pan of panels) {
    const btn = document.createElement("button");
    btn.textContent = pan.title;
    btn.dataset.panel = pan.id;
    btn.onclick = () => showPanel(pan.id);
    nav.append(btn);
    if (pan.id === "log") continue;
    const div = document.createElement("div");
    div.id = `panel-${pan.id}`;
    div.hidden = true;
    main.append(div);
    if (pan.id === "help") {
      div.append($("helptext").content.cloneNode(true));
      continue;
    }
    if (pan.id === "system") {
      div.innerHTML = `<section class="sec"><h2>System and Setup (read from the synth, not editable here)</h2>
        <p class="help">Press "Read from synth" to fill this in. Change these on the synth's panel if needed.</p>
        <table class="ro" id="systable"></table></section>`;
      continue;
    }
    if (pan.id === "changes") {
      div.innerHTML = `<section class="sec"><h2>Changes since the last Read / Load / Open / New</h2>
        <p class="help">Reset (or ↺ next to a setting) puts one value back; effect settings come back as a whole effect.</p>
        <table class="ro changes" id="changetable"></table></section>
        <section class="sec sendbox" id="summary"></section>`;
      continue;
    }
    if (pan.id === "tones") {
      renderTones(div);
      continue;
    }
    if (pan.id === "effects") {
      div.append(effectsIntro());
      for (const kind of ["mfx", "chorus", "reverb"]) {
        effectViews[kind] = document.createElement("div");
        effectViews[kind].className = "effectview";
        div.append(effectViews[kind]);
      }
    }
    for (const s of pan.sections) {
      if (!s.params.length) continue;
      if (pan.id === "matrix" && s.params[0].startsWith("fm.pat.tone[")) continue; // shown as tone columns below
      const sec = section(s.id === "fx.chorus" ? s.title.replace(/^Chorus\b/, "Chorus/Delay") : s.title, s.help);
      const grid = sec.querySelector(".grid");
      for (const path of s.params) {
        const c = makeControl(path);
        if (c) grid.append(c);
      }
      if (pan.id === "effects") {
        const kind = { "fx.mfx": "mfx", "fx.mfx_control": "mfx", "fx.chorus": "chorus", "fx.reverb": "reverb" }[s.id];
        if (!kind) continue;
        effectViews[kind].append(sec);
        if (s.id !== "fx.mfx_control") {
          const holder = document.createElement("div");
          effectSections[kind] = holder;
          effectViews[kind].append(holder);
        }
        continue;
      }
      div.append(sec);
    }
    if (pan.id === "effects") setEffectView(effectView);
    if (pan.id === "matrix") {
      const first = pan.sections.find((s) => s.params.length && s.params[0].startsWith("fm.pat.tone[0]."));
      if (first) {
        div.append(columnHeader());
        div.append(toneTable("Matrix control switches per tone", "Which tones each matrix control affects.", first.params));
      }
    }
  }
  let seen = false;
  try { seen = localStorage.getItem("axsynth.seenHelp") === "1"; localStorage.setItem("axsynth.seenHelp", "1"); } catch { /* storage unavailable */ }
  let wanted = location.hash.slice(1); // e.g. #tones opens that tab
  if (/^tone\d$/.test(wanted)) wanted = "tones";
  showPanel([...$("tabs").children].some((x) => x.dataset.panel === wanted) ? wanted : seen ? "common" : "help");
}

// The four tones side by side: one row per setting, one column per tone.
function renderTones(div) {
  div.append(columnHeader());
  div.append(copyToneBar());
  for (const s of TONE_PANELS[0].sections) {
    if (!s.params.length) continue;
    div.append(toneTable(s.title, s.help, s.params));
  }
}

function toneTable(title, help, tone0Paths) {
  const sec = section(title, help, "tonegrid");
  const grid = sec.querySelector(".tonegrid");
  for (const path0 of tone0Paths) {
    const p = model.params[path0];
    if (p.control === "text") continue;
    const row = document.createElement("div");
    row.className = "trow" + (p.simple ? " simple" : "") + (p.level ? " level" : "");
    const label = document.createElement("div");
    label.className = "rowlabel";
    label.textContent = p.short || p.label;
    label.title = `${p.label}\n\n${p.help}`;
    row.append(label);
    for (let t = 0; t < 4; t++) {
      const c = makeControl(tonePath(path0, t), true);
      c.classList.add(`col${t}`);
      row.append(c);
    }
    grid.append(row);
  }
  return sec;
}

// Column headers with "edit together" selection (shared by every tone table).
function columnHeader() {
  const bar = document.createElement("div");
  bar.className = "colheader";
  const lead = document.createElement("div");
  lead.className = "rowlabel";
  lead.innerHTML = `<b>Edit together:</b><br><span class="hint">tick columns; a change in a ticked column goes to all ticked columns</span>`;
  bar.append(lead);
  for (let t = 0; t < 4; t++) {
    const head = document.createElement("div");
    head.className = `colhead col${t}`;
    const l = document.createElement("label");
    const cb = document.createElement("input");
    cb.type = "checkbox";
    cb.dataset.tone = t;
    cb.onchange = () => setLinked(t, cb.checked);
    l.append(cb, ` Tone ${t + 1}`);
    l.title = "Tick to edit this tone together with the other ticked tones";
    const state = document.createElement("button");
    state.className = "tonestate";
    state.dataset.tone = t;
    state.title = "Switch this tone on or off (TONE SWITCH)";
    state.onclick = () => {
      const path = `fm.pat.tmt.tmtToneSwitch[${t}]`;
      onChange(path, patch.get(path) ? 0 : 1);
      scheduleStatus();
    };
    head.append(l, state);
    bar.append(head);
  }
  return bar;
}

function copyToneBar() {
  const bar = document.createElement("div");
  bar.className = "copybar";
  const sel = (id, def) => `<select id="${id}">${[0, 1, 2, 3].map((t) => `<option value="${t}"${t === def ? " selected" : ""}>Tone ${t + 1}</option>`).join("")}</select>`;
  bar.innerHTML = `<b>Copy a tone:</b> all settings of ${sel("copyfrom", 0)} → to ${sel("copyto", 1)} <button id="copytone">Copy</button>
    <span class="hint">(its wave, filter, amp, LFOs, … and key/velocity range; the target's ON/OFF stays)</span>`;
  bar.querySelector("#copytone").onclick = copyTone;
  return bar;
}

async function copyTone() {
  const from = Number($("copyfrom").value), to = Number($("copyto").value);
  if (from === to) { await confirmBox("Choose two different tones", "Pick a source and a different target tone.", "OK"); return; }
  if (!(await confirmBox(`Copy Tone ${from + 1} to Tone ${to + 1}?`,
    `Every setting of Tone ${to + 1} is replaced by Tone ${from + 1}'s. (Undo with ↺ or the Changes tab.)`, "Copy"))) return;
  try {
    dropPending(`tone[${to}]`);
    const { block, changes } = patch.copyTone(from, to);
    sendNow(block.address, block.data);
    changes.forEach(transmit);
    refresh();
    log(`copied Tone ${from + 1} to Tone ${to + 1}`);
  } catch (e) {
    fail(e);
  }
}

function setLinked(t, on) {
  if (on) linked.add(t);
  else linked.delete(t);
  for (const cb of document.querySelectorAll(`.colheader input[data-tone="${t}"]`)) cb.checked = on;
  document.body.classList.toggle(`sel${t}`, on);
}

function effectsIntro() {
  const box = document.createElement("section");
  box.className = "sec routingbox";
  box.innerHTML = `<h2>Signal path</h2>
    <p class="help">Click <b>MFX</b>, <b>Chorus/Delay</b> or <b>Reverb</b> to show its settings below; click a <b>Tone</b> to go to the Tones tab;
      click an <u>underlined value</u> on an arrow to change it right here.</p>
    <div id="diagram"></div>
    <div class="assignrow" id="assignrow"><div class="assignhead"><b>Where the tones go</b>
      <span class="hint">OUTPUT ASSIGN: MFX = through the multi-effect; L+R / L / R = straight to the output. The per-tone settings only apply when the sound's OUTPUT ASSIGN is TONE.</span></div></div>
    <ul class="routing" id="routing"></ul>
    <p class="help">One MFX, one chorus and one reverb per sound. A second modulation effect: use the tones' LFOs
    (Tones tab → LFO: DEPTH TVA = tremolo, DEPTH PAN = auto-pan, DEPTH PITCH = vibrato) or an MFX combination
    (27 TREMOLO CHORUS, 66–77).</p>`;
  box.querySelector("#diagram").addEventListener("click", onDiagramClick);
  const row = box.querySelector("#assignrow");
  const grid = document.createElement("div");
  grid.className = "assigngrid";
  const whole = makeControl("fm.pat.common.patchOutputAssign");
  whole.querySelector("label").textContent = "Whole sound";
  grid.append(whole);
  for (let t = 0; t < 4; t++) {
    const c = makeControl(`fm.pat.tone[${t}].toneOutputAssign`);
    c.querySelector("label").textContent = `Tone ${t + 1}`;
    c.classList.add("toneassign");
    grid.append(c);
  }
  row.append(grid);
  return box;
}

// Diagram clicks: boxes select an effect (or open the Tones tab); values open a small editor.
function onDiagramClick(ev) {
  const go = ev.target.closest("[data-go]");
  const edit = ev.target.closest("[data-edit]");
  if (edit) { openEdgeEditor(edit.dataset.edit, ev); return; }
  if (!go) return;
  if (go.dataset.go === "tones") showPanel("tones");
  else setEffectView(go.dataset.go);
}

function edgePaths(key) {
  const sp = signalPath(patch);
  const tones = sp.tones.filter((x) => x.on);
  const send = (t, unit) => `fm.pat.tone[${t.tone}].tone${unit}SendLevel${t.via ? "MFX" : "NonMFX"}`;
  return {
    toneCho: tones.map((t) => send(t, "Chorus")), toneRev: tones.map((t) => send(t, "Reverb")),
    mfxOut: ["fm.pat.mfx.mfxDrySendLevel"], mfxCho: ["fm.pat.mfx.mfxChorusSendLevel"], mfxRev: ["fm.pat.mfx.mfxReverbSendLevel"],
    outAssign: ["fm.pat.common.patchOutputAssign", ...[0, 1, 2, 3].map((t) => `fm.pat.tone[${t}].toneOutputAssign`)],
    choLevel: ["fm.pat.cho.chorusLevel"], choSel: ["fm.pat.cho.chorusOutputSelect"], revLevel: ["fm.pat.rev.reverbLevel"],
  }[key] || [];
}

let edgePop = null;
function closeEdgeEditor() {
  if (!edgePop) return;
  for (const r of edgePop.rows) removeControl(r.dataset.path, r.ctl);
  edgePop.el.remove();
  edgePop = null;
}
function openEdgeEditor(key, ev) {
  closeEdgeEditor();
  const paths = edgePaths(key);
  const el = document.createElement("div");
  el.className = "edgepop";
  el.innerHTML = `<div class="pophead"><b>Change here</b><span class="hint">same settings as on the Tones / Effects tabs</span><button class="close" title="Close">×</button></div>`;
  const rows = [];
  for (const path of paths) {
    const row = makeControl(path);
    const tone = path.match(/^fm\.pat\.tone\[(\d)\]/);
    if (tone) row.querySelector("label").textContent = `Tone ${+tone[1] + 1}: ${row.querySelector("label").textContent}`;
    row.ctl.update();
    rows.push(row);
    el.append(row);
  }
  if (!paths.length) el.append(Object.assign(document.createElement("p"), { textContent: "No tone is switched on." }));
  document.body.append(el);
  const x = Math.min(ev.clientX + 12, innerWidth - el.offsetWidth - 16);
  const y = Math.min(ev.clientY + 12, innerHeight - el.offsetHeight - 16);
  el.style.left = `${Math.max(8, x)}px`;
  el.style.top = `${Math.max(8, y)}px`;
  el.querySelector(".close").onclick = closeEdgeEditor;
  edgePop = { el, rows };
}
addEventListener("keydown", (e) => { if (e.key === "Escape") closeEdgeEditor(); });
addEventListener("mousedown", (e) => { if (edgePop && !edgePop.el.contains(e.target) && !e.target.closest("[data-edit]")) closeEdgeEditor(); });

function section(title, help, gridClass = "grid") {
  const sec = document.createElement("section");
  sec.className = "sec";
  sec.innerHTML = `<h2></h2><p class="help"></p><div class="${gridClass}"></div>`;
  sec.querySelector("h2").textContent = title;
  sec.querySelector("p").textContent = help || "";
  return sec;
}

function renderEffects() {
  queueMicrotask(() => applyMode());
  for (const [kind, holder] of Object.entries(effectSections)) {
    for (const path of controls.keys()) {
      if (model.params[path].union && model.params[path].union[0] === kind && model.params[path].union[1] > 0) controls.delete(path);
    }
    holder.innerHTML = "";
    const n = patch.effectType(kind);
    const t = model.effects[kind].types.find((x) => x.number === n);
    if (!t || !t.params.length) continue;
    const unit = { mfx: "MFX", chorus: "CHORUS/DELAY", reverb: "REVERB" }[kind];
    const sec = section(`${unit} ${n}: ${t.name}${t.category ? ` (${t.category})` : ""}`, t.description);
    const grid = sec.querySelector(".grid");
    for (const path of t.params) {
      const c = makeControl(path);
      if (c) grid.append(c);
    }
    holder.append(sec);
  }
}

function showPanel(id) {
  for (const b of $("tabs").children) b.classList.toggle("active", b.dataset.panel === id);
  for (const d of $("panels").children) d.hidden = d.id !== `panel-${id}`;
  $("logpanel").hidden = id !== "log";
}

// ---------------------------------------------------------------- simple / expert mode
function expert() {
  return $("expert").checked;
}
function applyMode() {
  const simple = !expert();
  document.body.classList.toggle("simple", simple);
  document.body.classList.toggle("expert", !simple);
  for (const sec of document.querySelectorAll("#panels section.sec")) {
    const items = sec.querySelectorAll(".grid > .ctl, .trow");
    sec.hidden = simple && items.length > 0 && !sec.querySelector(".grid > .ctl.simple, .trow.simple");
  }
  for (const b of $("tabs").children) {
    const pan = model.panels.find((p) => p.id === b.dataset.panel);
    if (pan) b.hidden = simple && !pan.sections.some((s) => s.params.some((x) => model.params[x].simple));
    if (b.dataset.panel === "system" || b.dataset.panel === "log") b.hidden = simple;   // expert-only tabs
    const pan2 = model.panels.find((p) => p.id === b.dataset.panel);
    const expertOnly = ["system", "log"].includes(b.dataset.panel) ||
      (pan2 && !pan2.sections.some((s) => s.params.some((x) => model.params[x].simple)));
    b.classList.toggle("tab-expert", expertOnly);
    b.classList.toggle("tab-simple", !expertOnly);
  }
  const current = [...$("tabs").children].find((b) => b.classList.contains("active"));
  if (current && current.hidden) showPanel("common");
  if (simple && !$("logpanel").hidden) showPanel("common");
  try { localStorage.setItem("axsynth.expert", expert() ? "1" : "0"); } catch { /* storage unavailable */ }
}

// ---------------------------------------------------------------- status: routing + changes + summary
let statusFrame = 0;
function scheduleStatus() {
  if (!statusFrame) statusFrame = requestAnimationFrame(() => { statusFrame = 0; updateStatus(); });
}
let refreshFrame = 0;
function scheduleRefresh() {
  if (!refreshFrame) refreshFrame = requestAnimationFrame(() => { refreshFrame = 0; refresh(); });
}

function updateStatus() {
  const r = routing(patch, setup);
  const ul = $("routing");
  ul.innerHTML = "";
  for (const item of r.filter((x) => x.level === "warn")) {
    const li = document.createElement("li");
    li.className = item.level;
    li.textContent = `⚠ ${item.text}`;
    ul.append(li);
  }
  $("diagram").innerHTML = diagram(signalPath(patch));
  const byTone = patch.get("fm.pat.common.patchOutputAssign") === 13;
  for (const el of document.querySelectorAll("#assignrow .toneassign")) el.classList.toggle("inactive", !byTone);
  const warn = r.some((x) => x.level === "warn");
  tab("effects").textContent = `${model.panels.find((p) => p.id === "effects").title}${warn ? " ⚠" : ""}`;

  const sp = signalPath(patch);
  for (const el of document.querySelectorAll(".tonestate")) {
    const on = sp.tones[Number(el.dataset.tone)].on;
    el.textContent = on ? "ON" : "OFF";
    el.className = `tonestate ${on ? "on" : "off"}`;
  }

  const changes = patch.diff(original);
  tab("changes").textContent = `Changes (${changes.length})`;
  const table = $("changetable");
  table.innerHTML = "";
  for (const c of changes) {
    const p = model.params[c.path];
    const tr = document.createElement("tr");
    const where = c.path.replace(/^fm\.pat\./, "").replace(/^tone\[(\d)\]\..*/, (_, t) => `Tone ${+t + 1}`).split(".")[0];
    tr.innerHTML = `<td></td><td></td><td></td><td></td><td></td>`;
    tr.children[0].textContent = where;
    tr.children[1].textContent = p.short || p.label;
    tr.children[2].textContent = display(p, c.from, model.waves);
    tr.children[3].textContent = `→ ${display(p, c.to, model.waves)}`;
    const b = document.createElement("button");
    b.textContent = "Reset";
    b.onclick = () => resetOne(c.path);
    tr.children[4].append(b);
    table.append(tr);
  }
  if (!changes.length) table.innerHTML = `<tr><td>No changes.</td></tr>`;
  renderSummary(changes.length);
}
function tab(id) {
  return [...$("tabs").children].find((b) => b.dataset.panel === id);
}

// Summary at the bottom of the Changes page: what the synth has and how to send it all.
function renderSummary(n) {
  const box = $("summary");
  const live = $("live").checked;
  const state = !connected
    ? "The editor isn't connected, so nothing has been sent yet."
    : live
      ? `Your changes were sent live, one at a time, so the synth should already sound like this.`
      : `"Send changes live" is off: the synth still plays the sound from before your changes.`;
  box.innerHTML = `<h2>Summary</h2>
    <p><b>${n}</b> change${n === 1 ? "" : "s"} to "<b class="pname"></b>". ${state}</p>
    <div class="sendrow"><button class="sendbig">⬆ Send whole sound to synth + check</button><span class="verify"></span></div>
    <p class="help"><b>What does sending do?</b> It <b>replaces the sound the synth is playing right now</b> (its working copy)
    with exactly what you see here, then reads it back and compares, so you get a ✓ when the synth has it.
    Sending never touches your <b>256 stored sounds</b> (only "Store in synth slot" does). Selecting another sound on the keytar brings back the stored version
    and discards this one.</p>
    <h3>Happy with it? Keep it</h3>
    <ol class="keep">
      <li><b>Save .a8e</b> (top of the page): stores the sound as a file on this computer. You can open it here any time.</li>
      <li>To store it <b>inside the synth</b> (so it's there without the computer): click <b>Store in synth slot…</b> (top of the page),
        choose one of the 256 memory slots, and confirm. The slot's old sound is <b>replaced</b>; the editor downloads it as a file first,
        then writes and checks. Afterwards, switch the synth off and on and load that slot to make sure it stuck.</li>
    </ol>
    <div class="row"><button id="store2" class="storebtn"${connected ? "" : " disabled"}>Store in synth slot…</button><button id="revertall2">Revert all changes</button></div>`;
  box.querySelector(".pname").textContent = patch.name();
  box.querySelector(".sendbig").onclick = () => sendWholePatch().catch(fail);
  box.querySelector("#revertall2").onclick = revertAll;
  box.querySelector("#store2").onclick = openStore;
  if (lastVerify) setVerify(lastVerify.ok ? `✓ Last check: the synth had exactly "${lastVerify.name}" (${lastVerify.when.toLocaleTimeString()}).`
                                           : "✗ The last check found a difference.", lastVerify.ok ? "ok" : "bad");
}

// ---------------------------------------------------------------- routing diagram (SVG)
function diagram(sp) {
  const W = 760, H = 250;
  const act = "var(--ok)", idle = "var(--line2)";
  const esc = (s) => String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);
  const box = (x, y, w, h, title, sub, on, go) =>
    `<g class="node ${on ? "on" : "off"}${go ? " link" : ""}${go && go === effectView ? " sel" : ""}"${go ? ` data-go="${go}"` : ""}>` +
    `<title>${go === "tones" ? "Open the Tones tab" : go ? "Show these settings below" : ""}</title><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="6"/>` +
    `<text x="${x + w / 2}" y="${y + (sub ? h / 2 - 3 : h / 2 + 4)}" class="t">${esc(title)}</text>` +
    (sub ? `<text x="${x + w / 2}" y="${y + h / 2 + 12}" class="s">${esc(sub)}</text>` : "") + `</g>`;
  const edge = (x1, y1, x2, y2, on, label, lx, ly, key) => {
    const mx = (x1 + x2) / 2;
    return `<path d="M${x1},${y1} C${mx},${y1} ${mx},${y2} ${x2},${y2}" fill="none" stroke="${on ? act : idle}" stroke-width="${on ? 2.2 : 1.2}"` +
      `${on ? "" : ' stroke-dasharray="4 4"'} marker-end="url(#${on ? "a1" : "a0"})"/>` +
      (label ? `<text x="${lx ?? mx}" y="${ly ?? (y1 + y2) / 2 - 4}" class="e ${on ? "on" : ""}${key ? " link" : ""}"${key ? ` data-edit="${key}"` : ""}>` +
        `${key ? "<title>Click to change</title>" : ""}${esc(label)}</text>` : "");
  };
  const tonesY = (t) => 18 + t * 56;
  const mfx = { x: 250, y: 92, w: 150, h: 54 };
  const cho = { x: 470, y: 18, w: 150, h: 48 };
  const rev = { x: 470, y: 176, w: 150, h: 48 };
  const out = { x: 680, y: 92, w: 70, h: 54 };
  const mfxOn = sp.mfx.type !== 0;
  const choOn = sp.chorus.type !== 0 && sp.chorus.level > 0;
  const revOn = sp.reverb.type !== 0 && sp.reverb.level > 0;
  let s = `<svg viewBox="0 0 ${W} ${H}" class="diagram" role="img" aria-label="Signal path"><defs>` +
    `<marker id="a1" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0,0L10,5L0,10z" fill="${act}"/></marker>` +
    `<marker id="a0" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0L10,5L0,10z" fill="${idle}"/></marker></defs>`;
  const via = sp.tones.filter((t) => t.on && t.via);
  const pa = patch.get("fm.pat.common.patchOutputAssign");
  const paName = (model.params["fm.pat.common.patchOutputAssign"].enum || [])[
    (model.params["fm.pat.common.patchOutputAssign"].enumValues || []).indexOf(pa)] ?? pa;
  s += `<text x="190" y="${H - 6}" class="e link" data-edit="outAssign"><title>Click to change</title>output assign: ${esc(paName)}</text>`;
  for (const t of sp.tones) {
    const y = tonesY(t.tone) + 20;
    if (t.on && t.via) s += edge(130, y, mfx.x, mfx.y + mfx.h / 2, t.out > 0);
    if (t.on && !t.via) s += edge(130, y, out.x, out.y + 10 + t.tone * 10, t.out > 0, t.tone === 0 ? "direct (bypasses MFX)" : "", 400, 60);
  }
  const choSends = sp.tones.filter((t) => t.on).map((t) => `${t.tone + 1}:${t.cho}`).join(" ");
  const revSends = sp.tones.filter((t) => t.on).map((t) => `${t.tone + 1}:${t.rev}`).join(" ");
  const anyCho = sp.tones.some((t) => t.on && t.cho > 0);
  const anyRev = sp.tones.some((t) => t.on && t.rev > 0);
  s += edge(130, 40, cho.x, cho.y + 14, anyCho && choOn, `tone sends ${choSends || "–"}`, 300, 22, "toneCho");
  s += edge(130, 190, rev.x, rev.y + 34, anyRev && revOn, `tone sends ${revSends || "–"}`, 300, 232, "toneRev");
  const mfxLive = via.length > 0;
  s += edge(mfx.x + mfx.w, mfx.y + 27, out.x, out.y + 27, mfxLive && sp.mfx.out > 0, `out ${sp.mfx.out}`, undefined, undefined, "mfxOut");
  s += edge(mfx.x + mfx.w, mfx.y + 8, cho.x, cho.y + 34, mfxLive && sp.mfx.cho > 0 && choOn, `send ${sp.mfx.cho}`, 440, 80, "mfxCho");
  s += edge(mfx.x + mfx.w, mfx.y + 46, rev.x, rev.y + 14, mfxLive && sp.mfx.rev > 0 && revOn, `send ${sp.mfx.rev}`, 440, 168, "mfxRev");
  const choFed = choOn && (anyCho || (mfxLive && sp.mfx.cho > 0));
  s += edge(cho.x + cho.w, cho.y + 24, out.x, out.y + 12, choFed && sp.chorus.toMain, `level ${sp.chorus.level}`, undefined, undefined, "choLevel");
  const sel = ["MAIN", "MAIN+REV", "REV"][patch.get("fm.pat.cho.chorusOutputSelect")] || "";
  s += edge(cho.x + 75, cho.y + cho.h, rev.x + 75, rev.y, choFed && sp.chorus.toReverb && revOn, `output: ${sel}`, cho.x + 28, 150, "choSel");
  s += edge(rev.x + rev.w, rev.y + 24, out.x, out.y + 42, revOn, `level ${sp.reverb.level}`, undefined, undefined, "revLevel");
  for (const t of sp.tones) {
    s += box(20, tonesY(t.tone), 110, 40, `Tone ${t.tone + 1}${t.on ? "" : " (off)"}`, t.on ? (t.wave ? model.waves[t.wave - 1] : "no wave") : "", t.on, "tones");
  }
  s += box(mfx.x, mfx.y, mfx.w, mfx.h, "MFX", sp.mfx.type ? sp.mfx.name : "THROUGH (no effect)", mfxOn, "mfx");
  s += box(cho.x, cho.y, cho.w, cho.h, "Chorus/Delay", sp.chorus.type ? sp.chorus.name : "OFF", choOn, "chorus");
  s += box(rev.x, rev.y, rev.w, rev.h, "Reverb", sp.reverb.type ? sp.reverb.name : "OFF", revOn, "reverb");
  s += box(out.x, out.y, out.w, out.h, "OUTPUT", "", true);
  return s + "</svg>";
}

// ---------------------------------------------------------------- store in a memory slot
// The only write outside the Temporary Patch (user request 2026-09-28). Order:
// backup ticked -> read + download the slot's current sound -> final "are you
// sure" -> 9 whole-block DT1s (Roland's Librarian format) -> read back + compare.
const slotLabel = (n) => { const f = model.factory.find((x) => x.n === n); return f ? `${f.slot}` : String(n); };
let storeReadToken = 0;

function openStore() {
  const sel = $("store-slot");
  if (!sel.options.length) {
    for (const f of model.factory) sel.add(new Option(`${f.slot}  (factory: ${f.name}, ${f.family})`, f.n));
    sel.onchange = () => readSlotName();
    $("store-backup").onchange = updateStoreButton;
    $("store-cancel").onclick = () => $("storedlg").close();
    $("store-go").onclick = () => storeInSlot().catch((e) => { fail(e); setStoreResult(`✗ ${e.message}`, "bad"); });
  }
  if (lastSlot !== null) sel.value = String(lastSlot);
  $("store-backup").checked = false;
  setStoreResult("", "");
  $("storedlg").showModal();
  readSlotName();
}

let slotName = null;
async function readSlotName() {
  const n = Number($("store-slot").value);
  const token = ++storeReadToken;
  slotName = null;
  $("store-current").textContent = "Currently in this slot: reading…";
  updateStoreButton();
  try {
    const common = await synth.request(userPatchAddress(n), model.blocks[0].size);
    if (token !== storeReadToken) return;
    slotName = String.fromCharCode(...common.slice(0, 12)).trimEnd();
    $("store-current").innerHTML = `Currently in slot ${slotLabel(n)}: <b></b> (will be replaced by "<b></b>")`;
    const bs = $("store-current").querySelectorAll("b");
    bs[0].textContent = `"${slotName}"`;
    bs[1].textContent = patch.name();
  } catch (e) {
    if (token === storeReadToken) $("store-current").textContent = `Couldn't read the slot (${e.message}). Nothing can be stored until it can be read.`;
  }
  updateStoreButton();
}

function updateStoreButton() {
  $("store-go").disabled = !(connected && slotName !== null && $("store-backup").checked);
}
function setStoreResult(text, cls) {
  $("store-result").textContent = text;
  $("store-result").className = `verify ${cls}`;
}

async function storeInSlot() {
  const n = Number($("store-slot").value);
  const label = slotLabel(n);
  if (!(await confirmBox(`Replace "${slotName}" in slot ${label}?`,
    `The synth's stored sound in slot ${label} is replaced by "${patch.name()}". The old one is downloaded as a file first.`, "Replace it"))) return;
  $("store-go").disabled = true;
  pending.clear();
  // 1. backup of this slot (read all 9 blocks, download as .a8e) - abort if it fails
  setStoreResult(`Backing up slot ${label}…`, "busy");
  const old = await readBlocks(userPatchAddress(n));
  const stamp = new Date().toISOString().slice(0, 16).replace(/[:T]/g, "-");
  download(old.toA8e(null), `slot-${label}-${old.name().replace(/[^\w.-]+/g, "_") || "patch"}-backup-${stamp}.a8e`);
  log(`backup of slot ${label} "${old.name()}" downloaded`);
  // 2. write the 9 whole blocks, like Roland's Librarian export
  setStoreResult(`Writing "${patch.name()}" to slot ${label}…`, "busy");
  for (const b of model.blocks) await synth.send(buildUserPatchDT1(n, b.offset, Array.from(patch.blocks[b.name])), 60);
  await new Promise((r) => setTimeout(r, 200));
  // 3. read back and compare
  const bad = [];
  for (const b of model.blocks) {
    const got = await synth.request(userPatchAddress(n) + b.offset, b.size);
    if (hex(got) !== hex(patch.blocks[b.name])) bad.push(b.name);
  }
  if (bad.length) {
    setStoreResult(`✗ Slot ${label} doesn't match after writing (${bad.join(", ")}). The backup file of the old sound was downloaded.`, "bad");
    log(`store FAILED for slot ${label}: ${bad.join(", ")}`);
  } else {
    setStoreResult(`✓ Stored "${patch.name()}" in slot ${label} and read it back. To be sure it survives power-off: switch the synth off and on, then Load slot ${label}.`, "ok");
    log(`stored "${patch.name()}" in slot ${label} (verified by read-back)`);
    slotName = patch.name();
  }
  updateStoreButton();
}

function download(bytes, filename) {
  const blob = new Blob([bytes], { type: "application/octet-stream" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 1000);
}

// ---------------------------------------------------------------- reset / revert / refresh
function resetOne(path) {
  const p = model.params[path];
  try {
    const kind = p.union ? p.union[0] : effectKindOf(path);
    if (kind && (p.union ? p.union[1] > 0 : true)) {
      // effect type or member: restore the whole effect block (Editor pattern: block, then type byte)
      dropPending(p.block);
      patch.blocks[p.block] = Uint8Array.from(original.blocks[p.block]);
      const disc = model.params[model.effects[kind].discriminator];
      sendNow(patch.blockAddress(p.block), patch.blocks[p.block]);
      sendNow(patch.address(disc), encodeValue(disc, patch.effectType(kind)));
      renderEffects();
    } else {
      transmit(patch.set(path, original.get(path), false));
    }
    refresh();
  } catch (e) {
    fail(e);
  }
}

async function revertAll(ask = true) {
  if (ask && !(await confirmBox("Revert all changes?", `Puts every setting back to how "${original.name()}" was when you loaded it, and sends that to the synth.`, "Revert all"))) return;
  patch = original.clone();
  renderEffects();
  refresh();
  if (connected) sendWholePatch().catch(fail);
}

function refresh() {
  $("name").value = patch.name();
  for (const list of controls.values()) for (const c of list) c.update();
  updateStatus();
}

function renderSystem(areas) {
  const rows = model.readonly.params.map((p) => {
    const bytes = areas[p.area];
    if (!bytes) return "";
    const v = bytes.slice(p.offset, p.offset + p.size).reduce((a, b) => a * (p.type === "int4x4" ? 16 : 128) + b, 0);
    return `<tr><td>${p.label}</td><td>${display(p, v, model.waves)}</td></tr>`;
  });
  $("systable").innerHTML = rows.join("");
  setup = {};
  for (const p of model.readonly.params) {
    if (p.area === "setup" && areas.setup) setup[p.path.split(".").pop()] = areas.setup[p.offset];
  }
}

// ---------------------------------------------------------------- actions
function setPatch(p, sendIt) {
  patch = p;
  original = p.clone();
  lastVerify = null;
  setVerify("", "");
  renderEffects();
  refresh();
  if (sendIt && connected) sendWholePatch().catch(fail);
}

$("connect").onclick = async () => {
  try {
    setStatus("connecting…", "off");
    const reply = await synth.connect(model.identityReply);
    connected = true;
    setStatus("Connected: Roland AX-Synth", "on");
    log(`Identity Reply ${hex(reply)}`);
    for (const id of ["read", "send", "loadslot", "store"]) $(id).disabled = false;
    $("connect").disabled = true;
    await readFromSynth();
  } catch (e) {
    fail(e);
  }
};

async function readFromSynth() {
  const p = await readBlocks(model.meta.temporaryPatch);
  const areas = {};
  for (const a of model.readonly.areas) areas[a.name] = await synth.request(addrToInt(a.address.split(" ").map((x) => parseInt(x, 16))), a.size);
  renderSystem(areas);
  setPatch(p, false);
  log(`read Temporary Patch "${patch.name()}"`);
}

$("read").onclick = async () => {
  if (unsaved() && !(await confirmBox("Read the synth's current sound?", `This replaces what you see here with the sound playing on the synth.${unsavedNote()}`, "Read"))) return;
  readFromSynth().catch(fail);
};
$("send").onclick = () => sendWholePatch().catch(fail);
$("live").onchange = () => scheduleStatus();
$("loadslot").onclick = async () => {
  try {
    const n = Number($("slot").value);
    const name = $("slot").selectedOptions[0].textContent.trim();
    if (!(await confirmBox(`Load "${name}"?`, `It replaces the sound you're editing and the synth starts playing it (the stored copy is only read, never changed).${unsavedNote()}`, "Load"))) return;
    const p = await readBlocks(userPatchAddress(n));
    lastSlot = n;
    log(`read stored sound ${n} "${p.name()}" (read-only); sending it to the Temporary Patch`);
    setPatch(p, true);
  } catch (e) {
    fail(e);
  }
};
$("init").onclick = async () => {
  if (!(await confirmBox("Start from a blank sound (INIT)?", `Replaces the sound you're editing with a plain starting sound and sends it to the synth.${unsavedNote()}`, "New sound"))) return;
  setPatch(Patch.initial(model), true);
};
$("open").onchange = async (ev) => {
  const f = ev.target.files[0];
  if (!f) return;
  try {
    const bytes = new Uint8Array(await f.arrayBuffer());
    const p = Patch.fromA8e(model, bytes);
    if (!(await confirmBox(`Open "${f.name}"?`, `Replaces the sound you're editing with "${p.name()}" and sends it to the synth.${unsavedNote()}`, "Open"))) { ev.target.value = ""; return; }
    a8eTemplate = bytes;
    log(`opened ${f.name}: "${p.name()}" (only the patch is sent, not the file's System/Setup)`);
    setPatch(p, true);
  } catch (e) {
    fail(e);
  }
  ev.target.value = "";
};
$("save").onclick = () => download(patch.toA8e(a8eTemplate), `${patch.name().replace(/[^\w.-]+/g, "_") || "patch"}.a8e`);
$("store").onclick = openStore;
$("name").onchange = () => {
  try {
    transmit(patch.set("fm.pat.common.patchName", $("name").value));
    scheduleStatus();
  } catch (e) {
    fail(e);
  }
};
$("copylog").onclick = () => navigator.clipboard.writeText(logEl.textContent);
$("clearlog").onclick = () => { logEl.textContent = ""; };

for (const t of model.factory) $("slot").add(new Option(`${t.slot}  ${t.name}  (${t.family})`, t.n));
try { $("expert").checked = localStorage.getItem("axsynth.expert") === "1"; } catch { /* storage unavailable */ }
if (new URLSearchParams(location.search).has("expert")) $("expert").checked = true;
$("expert").onchange = applyMode;
renderPanels();
renderEffects();
refresh();
applyMode();
// the tone column header sticks just below the (variable-height) page header
const setHdr = () => document.documentElement.style.setProperty("--hdr", `${document.querySelector("header").offsetHeight}px`);
setHdr();
addEventListener("resize", setHdr);
log(`model: ${Object.keys(model.params).length} parameters from ${model.meta.generator}`);
if (!navigator.requestMIDIAccess) setStatus("No Web MIDI in this browser: use Edge or Chrome", "err");
if (location.hash === "#store") openStore(); // shortcut (also used for screenshots)

// ?selftest: offline UI check with a fake MIDI output that records what
// would be sent. Logs one SELFTEST line (used by the headless-Edge check).
async function runSelftest() {
  const sent = [];
  synth.output = { send: (m) => sent.push(hex(m)) };
  connected = true;
  autoConfirm = true;
  const wait = (ms) => new Promise((r) => setTimeout(r, ms));
  const count = (kind) => effectSections[kind].querySelectorAll(".ctl").length;
  const res = [];
  for (const [kind, n] of [["mfx", 39], ["mfx", 63], ["chorus", 2], ["reverb", 3]]) {
    onChange(model.effects[kind].discriminator, n);
    res.push(`${kind}=${n}:${count(kind)}`);
  }
  await wait(200);
  // stale-edit check: drag a reverb member, then change the reverb type at once
  sent.length = 0;
  onChange("fm.pat.rev.srvHall-tm", 32800);
  onChange("fm.pat.rev.reverbType", 4);
  await wait(300);
  const last = sent[sent.length - 1] || "";
  res.push(`typeChangeMsgs=${sent.length} lastIsType=${last.startsWith("F0 41 10 00 00 3C 12 1F 00 06 00 04")}`);
  // routing: reverb on, sends zero -> warning + dashed reverb edges; send up -> ok
  patch.set("fm.pat.rev.reverbLevel", 100);
  for (let t = 0; t < 4; t++) patch.set(`fm.pat.tone[${t}].toneReverbSendLevelMFX`, 0);
  patch.set("fm.pat.mfx.mfxReverbSendLevel", 0);
  patch.set("fm.pat.cho.chorusOutputSelect", 0);
  patch.set("fm.pat.tmt.tmtToneSwitch[0]", 1);
  updateStatus();
  const revWarn = [...document.querySelectorAll("#routing li.warn")].some((li) => li.textContent.includes("Reverb"));
  patch.set("fm.pat.mfx.mfxReverbSendLevel", 60);
  updateStatus();
  const revOk = !document.querySelector("#routing li.warn") || ![...document.querySelectorAll("#routing li.warn")].some((li) => li.textContent.includes("Reverb"));
  const svg = $("diagram").querySelector("svg");
  res.push(`routingWarn=${revWarn} routingOk=${revOk} diagram=${!!svg} activeEdges=${svg.querySelectorAll('path[stroke="var(--ok)"]').length} effectsTab="${tab("effects").textContent}"`);
  // tone columns + edit together
  setLinked(0, true); setLinked(2, true);
  onChange("fm.pat.tone[0].tvfCutoffFrequency", 33);
  res.push(`linked=${[0, 1, 2, 3].map((t) => patch.get(`fm.pat.tone[${t}].tvfCutoffFrequency`)).join("/")}`);
  setLinked(0, false); setLinked(2, false);
  const rows = document.querySelectorAll("#panel-tones .trow");
  res.push(`toneRows=${rows.length} cellsPerRow=${new Set([...rows].map((r) => r.querySelectorAll(".cell").length)).size === 1 ? rows[0].querySelectorAll(".cell").length : "mixed"}`);
  // per-setting reset button
  const cutoff = "fm.pat.tone[1].tvfCutoffFrequency";
  const cell = document.querySelector(`.ctl[data-path="${cutoff}"]`);
  onChange(cutoff, 20);
  syncControls(cutoff);
  const shown = !cell.querySelector("button.reset").hidden;
  cell.querySelector("button.reset").click();
  res.push(`resetShown=${shown} resetBack=${patch.get(cutoff) === original.get(cutoff)} resetHidden=${cell.querySelector("button.reset").hidden}`);
  // simple / expert mode
  $("expert").checked = false; applyMode();
  const simpleTabs = [...$("tabs").children].filter((b) => !b.hidden).map((b) => b.dataset.panel).join(",");
  const hiddenSecs = document.querySelectorAll("#panels section.sec[hidden]").length;
  $("expert").checked = true; applyMode();
  res.push(`simpleRows=${document.querySelectorAll(".trow.simple").length} simpleCtls=${document.querySelectorAll(".grid > .ctl.simple").length}` +
           ` simpleTabs=${simpleTabs} hiddenSectionsSimple=${hiddenSecs} hiddenSectionsExpert=${document.querySelectorAll("#panels section.sec[hidden]").length}` +
           ` help=${$("panel-help").querySelectorAll("h3").length} helpMentionsMidiOx=${/MIDI-OX|Librarian/.test($("panel-help").textContent)}`);
  // changes + summary + revert
  updateStatus();
  const nChanges = patch.diff(original).length;
  const summary = $("summary").textContent.includes("replaces the sound the synth is playing right now");
  connected = false;
  await revertAll();
  res.push(`changes=${nChanges} summary=${summary} afterRevert=${patch.diff(original).length} tab="${tab("changes").textContent}"`);
  res.push(`controls=${document.querySelectorAll(".ctl").length}`);
  // dialog: renders and resolves (not auto-confirmed)
  autoConfirm = false;
  const answer = confirmBox("Test?", "text", "OK");
  const open = $("confirm").open;
  $("confirm-cancel").click();
  res.push(`dialogOpen=${open} dialogCancel=${(await answer) === false}`);
  // store dialog: opens, stays locked without backup tick and slot name
  openStore();
  const storeOpen = $("storedlg").open, lockedAtStart = $("store-go").disabled;
  $("store-backup").checked = true; updateStoreButton();
  const lockedWithoutName = $("store-go").disabled; // the (fake) synth never answers the slot read
  $("storedlg").close();
  res.push(`storeDialog=${storeOpen} storeLocked=${lockedAtStart && lockedWithoutName}`);
  // effect views follow the diagram; diagram values open an editor bound to the same setting
  showPanel("effects");
  const vis = () => Object.entries(effectViews).filter(([, v]) => !v.hidden).map(([k]) => k).join(",");
  const v0 = vis();
  $("diagram").querySelector('[data-go="reverb"]').dispatchEvent(new MouseEvent("click", { bubbles: true }));
  const v1 = vis();
  const selBox = $("diagram").querySelector(".node.sel")?.dataset.go;
  $("diagram").querySelector('[data-edit="revLevel"]').dispatchEvent(new MouseEvent("click", { bubbles: true, clientX: 300, clientY: 300 }));
  const popRange = document.querySelector(".edgepop input[type=range]");
  popRange.value = 77; popRange.dispatchEvent(new Event("input"));
  const mainRange = document.querySelector('#panel-effects .ctl[data-path="fm.pat.rev.reverbLevel"] input');
  res.push(`views=${v0}->${v1} selected=${selBox} shortcut=${patch.get("fm.pat.rev.reverbLevel")}/${mainRange.value}`);
  closeEdgeEditor();
  $("diagram").querySelector('[data-go="tones"]').dispatchEvent(new MouseEvent("click", { bubbles: true }));
  res.push(`toneBoxOpens=${tab("tones").classList.contains("active")}`);
  const sw = document.querySelector('.tonestate[data-tone="1"]');
  sw.click(); updateStatus();
  res.push(`toneSwitch=${patch.get("fm.pat.tmt.tmtToneSwitch[1]")}/${document.querySelector('.tonestate[data-tone="1"]').textContent}`);
  // copy a tone
  autoConfirm = true;
  patch.set("fm.pat.tone[0].tvfCutoffFrequency", 55);
  $("copyfrom").value = "0"; $("copyto").value = "3";
  await copyTone();
  res.push(`copyTone=${patch.get("fm.pat.tone[3].tvfCutoffFrequency")} blockEqual=${hex(patch.blocks["tone[3]"]) === hex(patch.blocks["tone[0]"])}`);
  // output assign shortcuts
  const whole = document.querySelector('#assignrow .ctl[data-path="fm.pat.common.patchOutputAssign"] select');
  whole.value = "13"; whole.dispatchEvent(new Event("change"));
  await wait(50); updateStatus();
  res.push(`assign=${patch.get("fm.pat.common.patchOutputAssign")} toneAssignActive=${!document.querySelector("#assignrow .toneassign.inactive")}` +
           ` tabColours=${[...$("tabs").children].map((b) => `${b.dataset.panel}:${b.classList.contains("tab-expert") ? "G" : "B"}`).join(",")}`);
  $("expert").checked = false; applyMode();
  res.push(`simpleHidesSystemLog=${tab("system").hidden && tab("log").hidden}`);
  log(`SELFTEST ${res.join(" ")}`);
}
if (new URLSearchParams(location.search).has("selftest")) runSelftest().catch((e) => log(`SELFTEST ERROR ${e.stack}`));
