// AX-Synth Web Editor: UI built from model.json (generated by
// research/tools/build_web_model.py from Roland's own data model).
import { buildDT1, hex, intToAddr, addrToInt, userPatchAddress } from "./sysex.js";
import { Synth } from "./midi.js";
import { Patch, display, options } from "./patch.js";

const $ = (id) => document.getElementById(id);
const logEl = $("log");
function log(text) {
  const t = new Date().toISOString().slice(11, 23);
  logEl.textContent += `${t} ${text}\n`;
  if (logEl.textContent.length > 400000) logEl.textContent = logEl.textContent.slice(-300000);
  logEl.scrollTop = logEl.scrollHeight;
}

const model = await (await fetch("model.json")).json();
let patch = Patch.initial(model);
let a8eTemplate = null; // bytes of the last opened .a8e (keeps its Setup/System on save)
const synth = new Synth(log);
let connected = false;
const controls = new Map(); // path -> {update()}

// ---------------------------------------------------------------- sending
const pending = new Map();
let flushTimer = null;
function transmit(change) {
  if (!connected || !$("live").checked) return;
  pending.set(change.address, change); // latest value per address wins while dragging
  if (!flushTimer) flushTimer = setTimeout(flush, 25);
}
function flush() {
  flushTimer = null;
  for (const c of pending.values()) synth.send(buildDT1(c.address, Array.from(c.data)), 10).catch(fail);
  pending.clear();
}
function fail(e) {
  console.error(e);
  log(`ERROR ${e.message}`);
  setStatus(e.message, "err");
}
function setStatus(text, cls) {
  const s = $("status");
  s.textContent = text;
  s.className = `status ${cls}`;
}

async function sendWholePatch() {
  pending.clear();
  $("verify").textContent = "sending…";
  $("verify").className = "verify";
  for (const b of model.blocks) {
    await synth.send(buildDT1(patch.blockAddress(b.name), Array.from(patch.blocks[b.name])), 60);
  }
  await new Promise((r) => setTimeout(r, 100));
  const bad = [];
  for (const b of model.blocks) {
    const got = await synth.request(patch.blockAddress(b.name), b.size);
    if (hex(got) !== hex(patch.blocks[b.name])) bad.push(b.name);
  }
  $("verify").textContent = bad.length ? `✗ read-back differs: ${bad.join(", ")}` : "✓ sent and verified";
  $("verify").className = `verify ${bad.length ? "bad" : "ok"}`;
  log(bad.length ? `verify FAILED for ${bad.join(", ")}` : "verify OK: the synth holds exactly the patch we sent");
}

async function readBlocks(base) {
  const blocks = {};
  for (const b of model.blocks) blocks[b.name] = await synth.request(base + b.offset, b.size);
  return new Patch(model, blocks);
}

// ---------------------------------------------------------------- controls
function makeControl(path) {
  const p = model.params[path];
  const row = document.createElement("div");
  row.className = "ctl" + (p.schemaOnly ? " schemaonly" : "");
  const label = document.createElement("label");
  label.textContent = p.label;
  label.title = `${p.help}\n\n${path}`;
  row.append(label);

  let input;
  const out = document.createElement("output");
  if (p.control === "select" || p.control === "wave" || p.control === "effectType" || isAssign(path)) {
    row.classList.add("wide");
    input = document.createElement("select");
    const fill = () => {
      input.innerHTML = "";
      for (const [v, text] of choiceList(path)) input.add(new Option(text, v));
    };
    fill();
    input.addEventListener("change", () => onChange(path, Number(input.value)));
    controls.set(path, { update: () => { if (isAssign(path)) fill(); input.value = String(patch.get(path)); } });
    row.append(input);
  } else if (p.control === "text") {
    return null;
  } else {
    input = document.createElement("input");
    input.type = "range";
    input.min = p.range[0];
    input.max = p.range[1];
    input.step = 1;
    input.addEventListener("input", () => {
      onChange(path, Number(input.value));
      out.value = display(p, Number(input.value), model.waves);
    });
    controls.set(path, { update: () => { const v = patch.get(path); input.value = v; out.value = display(p, v, model.waves); } });
    row.append(input, out);
  }
  input.title = label.title;
  return row;
}

function isAssign(path) {
  return /mfxControlAssign\d$/.test(path);
}

function choiceList(path) {
  const p = model.params[path];
  if (p.control === "wave") return [[0, "0: OFF"], ...model.waves.map((w, i) => [i + 1, `${i + 1}: ${w}`])];
  if (isAssign(path)) {
    const t = model.effects.mfx.types.find((x) => x.number === patch.effectType("mfx"));
    const labels = t && t.assign ? t.assign.labels : ["OFF"];
    return labels.map((l, i) => [i, l]);
  }
  if (p.control === "effectType") return p.enum.map((n, i) => [i, `${i}: ${n}`]);
  return options(p);
}

function onChange(path, value) {
  const p = model.params[path];
  try {
    if (p.control === "effectType") {
      const kind = p.union ? p.union[0] : Object.keys(model.effects).find((k) => model.effects[k].discriminator === path);
      const [block, type] = patch.changeEffectType(kind, value);
      if (connected && $("live").checked) {
        synth.send(buildDT1(block.address, block.data), 20).catch(fail);
        synth.send(buildDT1(type.address, Array.from(type.data)), 20).catch(fail);
      }
      renderEffects();
      refresh();
      return;
    }
    const changes = p.control === "wave" ? patch.setWave(path, value) : [patch.set(path, value)];
    changes.forEach(transmit);
  } catch (e) {
    fail(e);
  }
}

// ---------------------------------------------------------------- layout
const effectSections = {};
function renderPanels() {
  const nav = $("tabs");
  const main = $("panels");
  for (const pan of [...model.panels, { id: "system", title: "System (read-only)" }, { id: "log", title: "MIDI log" }]) {
    const btn = document.createElement("button");
    btn.textContent = pan.title;
    btn.dataset.panel = pan.id;
    btn.onclick = () => showPanel(pan.id);
    nav.append(btn);
    if (pan.id === "log") continue;
    const div = document.createElement("div");
    div.id = `panel-${pan.id}`;
    div.hidden = true;
    main.append(div);
    if (pan.id === "system") {
      div.innerHTML = `<section class="sec"><h2>System and Setup (read from the synth, not editable here)</h2>
        <p class="help">Press "Read from synth" to fill this in. Change these on the synth's panel if needed.</p>
        <table class="ro" id="systable"></table></section>`;
      continue;
    }
    for (const s of pan.sections) {
      if (!s.params.length) continue;
      const sec = section(s.title, s.help);
      const grid = sec.querySelector(".grid");
      for (const path of s.params) {
        const c = makeControl(path);
        if (c) grid.append(c);
      }
      div.append(sec);
      if (pan.id === "effects") {
        const kind = { "fx.mfx": "mfx", "fx.chorus": "chorus", "fx.reverb": "reverb" }[s.id];
        if (kind) {
          const holder = document.createElement("div");
          effectSections[kind] = holder;
          div.append(holder);
        }
      }
    }
  }
  showPanel("common");
}

function section(title, help) {
  const sec = document.createElement("section");
  sec.className = "sec";
  sec.innerHTML = `<h2></h2><p class="help"></p><div class="grid"></div>`;
  sec.querySelector("h2").textContent = title;
  sec.querySelector("p").textContent = help || "";
  return sec;
}

function renderEffects() {
  for (const [kind, holder] of Object.entries(effectSections)) {
    for (const path of controls.keys()) {
      if (model.params[path].union && model.params[path].union[0] === kind && model.params[path].union[1] > 0) controls.delete(path);
    }
    holder.innerHTML = "";
    const n = patch.effectType(kind);
    const t = model.effects[kind].types.find((x) => x.number === n);
    if (!t || !t.params.length) continue;
    const sec = section(`${kind.toUpperCase()} ${n}: ${t.name}${t.category ? ` (${t.category})` : ""}`, t.description);
    const grid = sec.querySelector(".grid");
    for (const path of t.params) {
      const c = makeControl(path);
      if (c) grid.append(c);
    }
    holder.append(sec);
  }
}

function showPanel(id) {
  for (const b of $("tabs").children) b.classList.toggle("active", b.dataset.panel === id);
  for (const d of $("panels").children) d.hidden = d.id !== `panel-${id}`;
  $("logpanel").hidden = id !== "log";
}

function refresh() {
  $("name").value = patch.name();
  for (const c of controls.values()) c.update();
}

function renderSystem(areas) {
  const rows = model.readonly.params.map((p) => {
    const bytes = areas[p.area];
    if (!bytes) return "";
    const v = bytes.slice(p.offset, p.offset + p.size).reduce((a, b) => a * (p.type === "int4x4" ? 16 : 128) + b, 0);
    return `<tr><td>${p.label}</td><td>${display(p, v, model.waves)}</td></tr>`;
  });
  $("systable").innerHTML = rows.join("");
}

// ---------------------------------------------------------------- actions
function setPatch(p, sendIt) {
  patch = p;
  renderEffects();
  refresh();
  if (sendIt && connected) sendWholePatch().catch(fail);
}

$("connect").onclick = async () => {
  try {
    setStatus("connecting…", "off");
    const reply = await synth.connect(model.identityReply);
    connected = true;
    setStatus("Connected: Roland AX-Synth", "on");
    log(`Identity Reply ${hex(reply)}`);
    for (const id of ["read", "send", "loadslot"]) $(id).disabled = false;
    $("connect").disabled = true;
    await readFromSynth();
  } catch (e) {
    fail(e);
  }
};

async function readFromSynth() {
  const p = await readBlocks(model.meta.temporaryPatch);
  const areas = {};
  for (const a of model.readonly.areas) areas[a.name] = await synth.request(addrToInt(a.address.split(" ").map((x) => parseInt(x, 16))), a.size);
  renderSystem(areas);
  setPatch(p, false);
  log(`read Temporary Patch "${patch.name()}"`);
}

$("read").onclick = () => readFromSynth().catch(fail);
$("send").onclick = () => sendWholePatch().catch(fail);
$("loadslot").onclick = async () => {
  try {
    const n = Number($("slot").value);
    const p = await readBlocks(userPatchAddress(n));
    log(`read stored sound ${n} "${p.name()}" (read-only); sending it to the Temporary Patch`);
    setPatch(p, true);
  } catch (e) {
    fail(e);
  }
};
$("init").onclick = () => setPatch(Patch.initial(model), true);
$("open").onchange = async (ev) => {
  const f = ev.target.files[0];
  if (!f) return;
  try {
    const bytes = new Uint8Array(await f.arrayBuffer());
    const p = Patch.fromA8e(model, bytes);
    a8eTemplate = bytes;
    log(`opened ${f.name}: "${p.name()}" (only the patch is sent, not the file's System/Setup)`);
    setPatch(p, true);
  } catch (e) {
    fail(e);
  }
  ev.target.value = "";
};
$("save").onclick = () => {
  const blob = new Blob([patch.toA8e(a8eTemplate)], { type: "application/octet-stream" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `${patch.name().replace(/[^\w.-]+/g, "_") || "patch"}.a8e`;
  a.click();
  URL.revokeObjectURL(a.href);
};
$("name").onchange = () => {
  try {
    transmit(patch.set("fm.pat.common.patchName", $("name").value));
  } catch (e) {
    fail(e);
  }
};
$("copylog").onclick = () => navigator.clipboard.writeText(logEl.textContent);
$("clearlog").onclick = () => { logEl.textContent = ""; };

for (const t of model.factory) $("slot").add(new Option(`${t.slot}  ${t.name}  (${t.family})`, t.n));
renderPanels();
renderEffects();
refresh();
log(`model: ${Object.keys(model.params).length} parameters from ${model.meta.generator}`);
if (!navigator.requestMIDIAccess) setStatus("No Web MIDI in this browser: use Edge or Chrome", "err");

// ?selftest: offline UI check (no MIDI): switch effect types, set a wave,
// edit a value, and log what was rendered.
if (new URLSearchParams(location.search).has("selftest")) {
  const count = (kind) => effectSections[kind].querySelectorAll(".ctl").length;
  const results = [];
  for (const [kind, n] of [["mfx", 39], ["mfx", 63], ["chorus", 2], ["reverb", 3]]) {
    onChange(model.effects[kind].discriminator, n);
    results.push(`${kind}=${n}:${count(kind)}`);
  }
  onChange("fm.pat.tone[0].waveNumberL", 61);
  onChange("fm.pat.tone[0].tvfCutoffFrequency", 40);
  const assign = [...document.querySelectorAll("select")].find((s) => s.title.includes("mfxControlAssign1"));
  log(`SELFTEST ${results.join(" ")} wave=${patch.get("fm.pat.tone[0].waveNumberL")}/${patch.get("fm.pat.tone[0].waveGroupID")}` +
      ` cutoff=${patch.get("fm.pat.tone[0].tvfCutoffFrequency")} assignOptions=${assign ? assign.options.length : "none"}` +
      ` controls=${document.querySelectorAll(".ctl").length}`);
}
